services:
  sample-app:
    build:
      context: ./apps/sample-app
    container_name: vulcan-sample-app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.27-alpine
    container_name: vulcan-nginx
    depends_on:
      - sample-app
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro