# docker/prometheus/prometheus.yml
global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "vulcan-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["vulcan-api:3000"]

  - job_name: "nginx-exporter"
    static_configs:
      - targets: ["nginx-exporter:9113"]